print("Merhaba", "Selam", "SoftwareLab", sep="_")
print("Merhaba", "Selam", "SoftwareLab", sep="*")
print("Merhaba", "Selam", "SoftwareLab", sep=".")
print("Merhaba", "Selam", "SoftwareLab", sep="    ")
print("Merhaba", "Selam", "SoftwareLab", sep="&")